//
//  Constants.swift
//  Score Keeper of Nottingham
//
//  Created by Drake Morin on 2020-09-03.
//  Copyright © 2020 Drake Morin. All rights reserved.
//

import Foundation

let POINTS_PER_APPLE = 2
let KING_BONUS_APPLE = 20
let QUEEN_BONUS_APPLE = 10

let POINTS_PER_CHEESE = 3
let KING_BONUS_CHEESE = 15
let QUEEN_BONUS_CHEESE = 10

let POINTS_PER_BREAD = 3
let KING_BONUS_BREAD = 15
let QUEEN_BONUS_BREAD = 10

let POINTS_PER_CHICKEN = 4
let KING_BONUS_CHICKEN = 10
let QUEEN_BONUS_CHICKEN = 5

let POINTS_PER_PEPPER = 6
let POINTS_PER_MEAD = 7
let POINTS_PER_SILK = 8
let POINTS_PER_CROSSBOW = 9

let POINTS_PER_GOLDEN_APPLES = 6
let APPLES_ON_GOLDEN_APPLES = 3
let POINTS_PER_GREEN_APPLES = 4
let APPLES_ON_GREEN_APPLES = 2

let POINTS_PER_BLUE_CHEESE = 9
let CHEESE_ON_BLUE_CHEESE = 3
let POINTS_PER_GOUDA = 6
let CHEESE_ON_GOUDA = 2

let POINTS_PER_PUMPERNICKEL = 9
let BREAD_ON_PUMPERNICKEL = 3
let POINTS_PER_RYE = 6
let BREAD_ON_RYE = 2

let POINTS_PER_DUAL_CHICKEN = 8
let CHICKENS_ON_DUAL_CHICKEN = 2
